version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 10485760
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  exporter:
    build: .
    volumes:
      - ./:/app
    environment:
      KAFKA_URL: kafka:9092
      ZOOKEEPER_URL: zookeeper:2181
      LEDGER: 12328458
      SEND_BATCH_SIZE: 500
      CONNECTIONS_COUNT: 10
      MAX_CONNECTION_CONCURRENCY: 50
      DEFAULT_WS_TIMEOUT: 20000